### ISSUE TITLE
Filtro tipo documento

### ISSUE THREAD

**Issue by WildemanHerrera1** [WildemanHerrera1/WildemanHerrera1.github.io#1]
Filtrar por tipo de documento si es persona natural solo mostrarle solo "RENTA PERSONAS NATURALES" y si es persona juridica mostrarle los otros la otra info sin "RENTA PERSONAS NATURALES"

**Comment by Wilson820** [comment]
Se agrega cambio en PR https://github.com/WildemanHerrera1/WildemanHerrera1.github.io/pull/2
